"""create users and strategies

Revision ID: 8bfdc01a6094
Revises:
Create Date: 2026-04-15 16:06:30.531619

NOTE: ondelete="CASCADE"는 데이터 무결성 안전망.
실제 흐름은 /auth/webhook의 user.deleted 에서 User.is_active=false +
Strategy.is_archived=true 로 soft delete. (spec §3.2 참조)
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8bfdc01a6094'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ENUM 타입을 명시적으로 생성 (create_type=False 로 테이블 생성 시 자동 생성 방지)
    # PostgreSQL 은 CREATE TYPE IF NOT EXISTS 를 지원하지 않으므로 DO 블록으로 처리
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE pineversion AS ENUM ('v4', 'v5');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
        """
    )
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE parsestatus AS ENUM ('ok', 'unsupported', 'error');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('pine_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pine_version', postgresql.ENUM('v4', 'v5', name='pineversion', create_type=False), nullable=False),
    sa.Column('parse_status', postgresql.ENUM('ok', 'unsupported', 'error', name='parsestatus', create_type=False), nullable=False),
    sa.Column('parse_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_is_archived'), 'strategies', ['is_archived'], unique=False)
    op.create_index('ix_strategies_owner_active_updated', 'strategies', ['user_id', 'is_archived', 'updated_at'], unique=False)
    op.create_index(op.f('ix_strategies_parse_status'), 'strategies', ['parse_status'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_parse_status'), table_name='strategies')
    op.drop_index('ix_strategies_owner_active_updated', table_name='strategies')
    op.drop_index(op.f('ix_strategies_is_archived'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ENUM 타입은 테이블 drop 후에 명시적으로 삭제해야 함
    # (Alembic autogenerate 는 ENUM drop 을 생략하는 경우가 있어 수동 추가)
    op.execute("DROP TYPE IF EXISTS pineversion")
    op.execute("DROP TYPE IF EXISTS parsestatus")
    # ### end Alembic commands ###
